server:  
  port: 20002  
eureka:  
  instance:  
    hostname: server2  
  client:  
    # 表示是否注册自身到eureka服务器  
    # register-with-eureka: false  
    # 是否从eureka上获取注册信息  
    # fetch-registry: false  
    service-url:
      #集群的话配另一台服务的host及port  
      defaultZone: http://server2:20002/eureka/
eureka.server.responseCacheUpdateInvervalMs: 3000
eureka.server.responseCacheAutoExpirationInSeconds: 180
eureka.server.eviction-interval-timer-in-ms: 3000